name: 构建

on: ["workflow_dispatch"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: go install github.com/9seconds/mtg/v2@latest
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          path: ./go
