name: 构建

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: go install github.com/9seconds/mtg/v2@latest
      - run: go env
      - uses: actions/upload-artifact@v3.1.2
        with:
          path: /home/go/bin
